name: CI – Tests

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main
      - github-actions

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (incl. pytest)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                   pip install pytest

      - name: Run tests
        run: |
          echo "Running tests..."
          if [ -d tests ]; then
            pytest -v
          else
            echo "No 'tests' directory found. Skipping pytest."
          fi
